#!/bin/bash

if [ $# -lt 1 ] || [ $# -gt 4 ]; then
  echo -e "usage: $0 \"c++ output code\" [\"initial c++ code\"] [\"compiler flags\"] [includes]"
  exit 42
fi

f="gpp$RANDOM"

binFile="$f.out"

gppBuild $f "$@" && $PWD/$binFile

rm $binFile
exit 0
